### ISSUE TITLE
Vertical metrics requirements

### ISSUE THREAD

**Issue by vv-monsalve** [petrvanblokland/TYPETR-Bitcount#12]
> FAIL OS/2.sTypoLineGap is "200" it should be 0 [code: bad-OS/2.sTypoLineGap] 
> FAIL OS/2.usWinAscent value should be equal or greater than 1000, but got 840 instead [code: ascent] 

The above Fails were reported for `Bitcount-Color[wght,ELXP,ELSH,slnt,SZP1,XPN1,YPN1,SZP2,XPN2,YPN2].ttf`

Please ensure all the fonts follow our [Vertical Metrics specifications](https://googlefonts.github.io/gf-guide/metrics)

**Comment by simoncozens** [comment]
This is fixed in #13.
