### ISSUE TITLE
FAIL:Check Google Fonts glyph coverage

### ISSUE THREAD

**Issue by vv-monsalve** [petrvanblokland/TYPETR-Bitcount#17]
<details><summary>🔥 <b>FAIL:</b> Check Google Fonts glyph coverage. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage">com.google.fonts/check/glyph_coverage</a>)</summary><div>

* 🔥 **FAIL** Missing required codepoints:

	- 0x0146 (LATIN SMALL LETTER N WITH CEDILLA)

	- 0x0237 (LATIN SMALL LETTER DOTLESS J)

	- 0x0300 (COMBINING GRAVE ACCENT)

	- 0x0301 (COMBINING ACUTE ACCENT)

	- 0x0302 (COMBINING CIRCUMFLEX ACCENT)

	- 0x0303 (COMBINING TILDE)

	- 0x0304 (COMBINING MACRON)

	- 0x0306 (COMBINING BREVE)

	- 0x0307 (COMBINING DOT ABOVE)

	- 0x0308 (COMBINING DIAERESIS)

	- 0x030A (COMBINING RING ABOVE)

	- 0x030B (COMBINING DOUBLE ACUTE ACCENT)

	- 0x030C (COMBINING CARON)

	- 0x0326 (COMBINING COMMA BELOW)

	- 0x0327 (COMBINING CEDILLA)

	- 0x0328 (COMBINING OGONEK)

	- 0x1E9E (LATIN CAPITAL LETTER SHARP S)
 [code: missing-codepoints]
</div></details>

<details><summary>🔥 <b>FAIL:</b> Shapes languages in all GF glyphsets. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyphsets/shape_languages">com.google.fonts/check/glyphsets/shape_languages</a>)</summary><div>

* 🔥 **FAIL** GF_Latin_Core glyphset:

| Language | FAIL messages |
| :--- | :--- |
| ca_Latn (Catalan) | Some mark glyphs were missing: ◌̀, ◌́, ◌̈, ◌̧ |
| cs_Latn (Czech) | Some mark glyphs were missing: ◌́, ◌̊, ◌̌ |
| cy_Latn (Welsh) | Some mark glyphs were missing: ◌̀, ◌́, ◌̂, ◌̈ |
| da_Latn (Danish) | Some mark glyphs were missing: ◌́, ◌̊ |
| de_Latn (German) | Some mark glyphs were missing: ◌̀, ◌́, ◌̈ |
| en_Latn (English) | Some mark glyphs were missing: ◌̀, ◌́, ◌̂, ◌̃, ◌̈, ◌̧ |
| es_Latn (Spanish) | Some mark glyphs were missing: ◌́, ◌̃, ◌̈ |
| fi_Latn (Finnish) | Some mark glyphs were missing: ◌̃, ◌̈, ◌̊, ◌̌ |
| fr_Latn (French) | Some mark glyphs were missing: ◌̀, ◌́, ◌̂, ◌̈, ◌̧ |
| hr_Latn (Croatian) | Some mark glyphs were missing: ◌́, ◌̌ |
| hu_Latn (Hungarian) | Some mark glyphs were missing: ◌́, ◌̈, ◌̋ |
| is_Latn (Icelandic) | Some mark glyphs were missing: ◌́, ◌̈, ◌̨ |
| it_Latn (Italian) | Some mark glyphs were missing: ◌̀, ◌́, ◌̂, ◌̈ |
| lt_Latn (Lithuanian) | Some mark glyphs were missing: ◌̄, ◌̇, ◌̌, ◌̨ |
| lv_Latn (Latvian) | Some base glyphs were missing: ņ |
|  ^  | Some mark glyphs were missing: ◌̄, ◌̌, ◌̧ |
|  ^  | Shaper produced a .notdef |
| mt_Latn (Maltese) | Some mark glyphs were missing: ◌̀, ◌̂, ◌̇ |
| nl_Latn (Dutch) | Some base glyphs were missing: íj́ |
|  ^  | Some mark glyphs were missing: ◌̀, ◌́, ◌̂, ◌̈ |
|  ^  | Shaper produced a .notdef |
| pl_Latn (Polish) | Some mark glyphs were missing: ◌́, ◌̇, ◌̨ |
| pt_Latn (Portuguese) | Some mark glyphs were missing: ◌̀, ◌́, ◌̂, ◌̃, ◌̈, ◌̧ |
| ro_Latn (Romanian) | Some mark glyphs were missing: ◌̂, ◌̆, ◌̦, ◌̧ |
| sk_Latn (Slovak) | Some mark glyphs were missing: ◌́, ◌̂, ◌̈, ◌̌ |
| sq_Latn (Albanian) | Some mark glyphs were missing: ◌̈, ◌̧ |
| sv_Latn (Swedish) | Some mark glyphs were missing: ◌̀, ◌́, ◌̈, ◌̊ |
| tr_Latn (Turkish) | Some mark glyphs were missing: ◌̂, ◌̆, ◌̇, ◌̈, ◌̦, ◌̧ |

 [code: failed-language-shaping]
* ⚠ **WARN** GF_Latin_Core glyphset:

| Language | FAIL messages |
| :--- | :--- |
| lv_Latn (Latvian) | Some auxiliary glyphs were missing: ņ |
| nb_Latn (Norwegian Bokmål) | No exemplar glyphs were defined for language Norwegian Bokmål |
| nl_Latn (Dutch) | Some auxiliary glyphs were missing: íj́ |

 [code: warning-language-shaping]
</div></details>

These two Fails are related to fulfilling the GF Latin Core, the ground requirement for language support.

cc @davelab6

**Comment by davelab6** [comment]
I've emailed Petr to discuss :)

**Comment by vv-monsalve** [comment]
Revisiting this reported Fails, I think the missing codepoints could be added in the next font version. @davelab6 wdyt?
