### ISSUE TITLE
WARN: Ensure fonts have ScriptLangTags declared on the 'meta' table

### ISSUE THREAD

**Issue by vv-monsalve** [petrvanblokland/TYPETR-Bitcount#21]
<details><summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags">com.google.fonts/check/meta/script_lang_tags</a>)</summary><div>

* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]
</div></details>

Adding a meta table is a strong suggestion, which would help to avoid [issues like this one](https://github.com/fonttools/fontbakery/issues/4644)

We are currently adding the script information by default, `Latn`. Now, if the font design includes any special `locl` for a specific language need, it should be specified in the `dlang`. 

In the ufo files, this goes in the `lib.plist`
```
    <key>public.openTypeMeta</key>
    <dict>
      <key>dlng</key>
      <array>
        <string>Latn</string>
      </array>
      <key>slng</key>
      <array>
        <string>Latn</string>
      </array>
    </dict>
```

**Comment by simoncozens** [comment]
You fixed this!
