### ISSUE TITLE
FAIL: Checking with ots-sanitize

### ISSUE THREAD

**Issue by vv-monsalve** [petrvanblokland/TYPETR-Bitcount#33]
This Fail is reported for the following fonts at the latest CI Run at commit 560a399.

<details>
    <summary>🔥 <b>FAIL</b> Checking with ots-sanitize. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/universal.sanitize.html#"></a></summary>
    <div>

* 🔥 **FAIL** <p>ots-sanitize returned an error code (1). Output follows:</p>
<p>ERROR: GSUB: Bad lookup offset 0 for lookup 0
ERROR: GSUB: Failed to parse lookup list table
ERROR: GSUB: Failed to parse table
Failed to sanitize file!</p>
 [code: ots-sanitize-error]

</div>
</details>

#### Affected fonts

- BitcountGridDoubleInk[CRSV,ELSH,ELXP,SZP1,SZP2,XPN1,XPN2,YPN1,YPN2,slnt,wght].ttf
- BitcountGridDouble[CRSV,ELSH,ELXP,slnt,wght].ttf

**Comment by simoncozens** [comment]
This is a known problem in ots-sanitize; some GSUB offsets are allowed to be NULL, but ots doesn't know that. We are also no longer using ots-sanitizer in latest Chrome, so this check should soon be deprecated.

**Comment by vv-monsalve** [comment]
Thank you for the clarification!
